stages:
  - build
  - test
  - deploy

# Build step
build-job:
  stage: build
  script:
    - echo "First Step"
    - echo "Second Step"

# Test step
test-job:
  stage: test
  script:
    - echo "Testing Step"

# Deploy step
deploy-job:
  stage: deploy
  script:
    - echo "Deploy Step"
